FROM hacklab/mapasculturais:v7.0-RC

COPY compose/common/config.d /var/www/config/common.d
COPY compose/production/config.d /var/www/config/prod.d

COPY themes /var/www/src/themes
COPY plugins /var/www/src/plugins